### ISSUE TITLE
refactor find_dividers (loop rearrangement / binary search where appropriate)

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/component_segmentation#20]
I think @lomereiter is already working on this one.

**Comment by subwaystation** [comment]
@lomereiter I can't assign you to the issue, so please test, if you could assign yourself.

**Comment by lomereiter** [comment]
Can't assign myself.

**Comment by subwaystation** [comment]
Now it worked somehow :)

**Comment by subwaystation** [comment]
Addressed via #27
