### ISSUE TITLE
refactor populate_component_matrix (loop rearrangement / binary search where appropriate)

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/component_segmentation#21]
@dimatr This is also work in progress, I figure.

**Comment by subwaystation** [comment]
I think I can only assign you @dimatr the moment you leave a comment here. @josiahseaman Would there be an easier way to do this?

**Comment by dimatr** [comment]
yep, doing this

**Comment by subwaystation** [comment]
Addressed via #26 .
