### ISSUE TITLE
referenced dataclass is not found

### ISSUE THREAD

**Issue by mr-c** [graph-genome/component_segmentation#51]
https://github.com/graph-genome/component_segmentation/commit/bcfc6a0a26486d60ebe54248075ff2da6605a053#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R22

There is no such package on PyPI with this name https://pypi.org/project/dataclass/

**Comment by dimatr** [comment]
true, should be "dataclasses"

**Comment by josiahseaman** [comment]
@dimatr did your push to setup.py fix this issue? This may be a good case for getting @Pigrenok involved in the testing loop now that he's going to be a primary maintainer.  Please close the issue once it's been merged to master and tested. Thanks!

**Comment by dimatr** [comment]
Yes, the fix has been pushed.

**Comment by Pigrenok** [comment]
@mr-c both setup.py (thanks @dimatr) and requirements.txt were updated. It should all work now.

**Comment by mr-c** [comment]
Thanks!
