### ISSUE TITLE
Change bin-size to bin-width so we have consistent naming across tools

### ISSUE THREAD

**Issue by subwaystation** [graph-genome/component_segmentation#6]
Reported by @6br in #5 . Thanks!

**Comment by josiahseaman** [comment]
Is odgi using the term bin-width?  To me, a size is pure math.  Whereas a width implies a physical object that's probably two dimensional, so it sounds more like a rendering parameter.

**Comment by subwaystation** [comment]
Yes, there is a `--bin-width` parameter in `odgi`.

**Comment by josiahseaman** [comment]
I'll take responsibility for this.  Since I'm updating file formats across tools anyways.
JSON_VERSION = 9
Note that at the moment, schematize is on branch i13_data_folders
